A <%= @exception.class %> occurred in <%= @controller.controller_name %>#<%= @controller.action_name %>:

  <%= @exception.message.to_s.html_safe! %>
  <%= @backtrace.first %>

<%= @sections.map { |section| render_section(section) }.join.html_safe! %>
